spring:
  application:
    name: REALTIME-ADAPTER-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: realtime-adapter-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.courthub.*

server:
  port: 8084
  servlet:
    context-path: /api/realtime

firebase:
  database-url: ${FIREBASE_DATABASE_URL}
  credentials-path: "classpath:courthub-db8c7-firebase-adminsdk-fbsvc-c01bf8b26a.json"

services:
  booking-url: ${BOOKING_SERVICE_URL:http://booking-service:8083}

logging:
  level:
    root: INFO
    com.courthub: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
